### ISSUE TITLE
希望增加revd_msg_s结构体对其中二维数组操作的帮助函数

### ISSUE THREAD

**Issue by macrovve** [callMePlus/ais_parse#2]

**Comment by macrovve** [comment]
用swig和python 混合编程时，revd_msg_s结构的`	char msg_p[5][1024];`没有办法直接赋值，希望添加函数来间接赋值。
```cpp
revd_msg_s(char *a,char *b,char *c,char *d,char *e)
{
	// Copy from ptr to array.
	strcpy(msg_p[0],a);
	strcpy(msg_p[1],b);
	strcpy(msg_p[2],c);
	strcpy(msg_p[3],d);
	strcpy(msg_p[4],e);
}
```
添加一个构造函数应该就够了

**Comment by leihui6** [comment]
这样的话有用么，我的意思是构造函数只有在初始化的时候才会被使用呀，那如果声明了，后面再使用的话怎么办呢，不太理解为什么这样就行了

**Comment by macrovve** [comment]
我的意思是python 没办法直接操作2维数组。需要你再提供函数来操作结构体的二维数组。上面代码我是举个例子，我当时只是想让它先跑起来试一下
